version: 2.1

jobs:
  build_and_test:
    docker:
      - image: rocker/verse:latest
    environment:
      R_LIBS_USER: /home/rstudio/R/Library
      TESTTHAT_REPORTER: "summary"
    steps:
      - checkout
      - restore_cache:
          keys:
            - r-pkg-cache-{{ arch }}-{{ checksum "DESCRIPTION" }}
            - r-pkg-cache-{{ arch }}-
      - run:
          name: Install dependencies
          command: |
            mkdir -p ${R_LIBS_USER}
            Rscript -e 'options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/bookworm/latest"))'
            Rscript -e 'if (!requireNamespace("pak", quietly = TRUE)) install.packages("pak")'
            Rscript -e 'pak::pkg_install(c("PolicyAnalysisInc/openqalytools", "PolicyAnalysisInc/openqalysurv", "PolicyAnalysisInc/openqalyregimen", "PolicyAnalysisInc/openqaly", "rcmdcheck", "sessioninfo"))'
            Rscript -e 'pak::local_install_deps(dependencies = TRUE)'
      - save_cache:
          key: r-pkg-cache-{{ arch }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/home/rstudio/R/Library"
      - run:
          name: Build and Check package
          no_output_timeout: 40m
          command: |
            Rscript -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "error", quiet = FALSE)'
      - store_artifacts:
          path: openqalyshiny.Rcheck/

  build_and_coverage:
    docker:
      - image: rocker/verse:latest
    environment:
      R_LIBS_USER: /home/rstudio/R/Library
    steps:
      - checkout
      - restore_cache:
          keys:
            - r-pkg-cache-{{ arch }}-{{ checksum "DESCRIPTION" }}
            - r-pkg-cache-{{ arch }}-
      - run:
          name: Install dependencies
          command: |
            mkdir -p ${R_LIBS_USER}
            Rscript -e 'options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/bookworm/latest"))'
            Rscript -e 'if (!requireNamespace("pak", quietly = TRUE)) install.packages("pak")'
            Rscript -e 'pak::pkg_install(c("PolicyAnalysisInc/openqalytools", "PolicyAnalysisInc/openqalysurv", "PolicyAnalysisInc/openqalyregimen", "PolicyAnalysisInc/openqaly", "covr"))'
            Rscript -e 'pak::local_install_deps(dependencies = TRUE)'
      - run:
          name: Code Coverage
          no_output_timeout: 60m
          command: |
            Rscript -e 'covr::codecov(quiet = FALSE)'

  js_tests:
    docker:
      - image: node:20
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install JS dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run JavaScript tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
      - build_and_coverage
      - js_tests
